### ISSUE TITLE
Peg-out success modal should close pop to root

### ISSUE THREAD

**Issue by torkelrogstad** [barebitcoin/sidesail#22]
<img width="976" alt="image" src="https://github.com/barebitcoin/sidesail/assets/16610775/d58f1a13-63d2-46ef-8542-8e95bf31f2cb">

Clicking "OK" here takes me back one step, to where I enter withdrawal details. I'd expect this to take me back to the root

**Comment by torkelrogstad** [comment]
Nvm, that doesn't appear to happen? It happen the first time though. Hm

**Comment by octobocto** [comment]
Very sure it does pop to root
