### ISSUE TITLE
TX list should scroll on overflow

### ISSUE THREAD

**Issue by torkelrogstad** [barebitcoin/sidesail#23]
<img width="976" alt="image" src="https://github.com/barebitcoin/sidesail/assets/16610775/5be886da-1fb5-4205-8900-81a216a7ace4">

I have more TXs than there's room for here. Should be able to scroll down, but I'm not

**Comment by octobocto** [comment]
are you saying you have more than 10 transactions?

**Comment by torkelrogstad** [comment]
Yes, more than 10 TXs. Realizing now that this is because the RPC only fetches 10 at a time by default?
