### ISSUE TITLE
Light mode on Linux startup looks wonky

### ISSUE THREAD

**Issue by torkelrogstad** [barebitcoin/sidesail#52]
Text next to the blue icon is unreadable

![image](https://github.com/barebitcoin/sidesail/assets/16610775/943235a7-0889-48b5-8308-ad257bd61a26)

**Comment by octobocto** [comment]
light mode in general looks really wonky

**Comment by octobocto** [comment]
Fixed in #67

**Comment by torkelrogstad** [comment]
Close this?
