### ISSUE TITLE
Light-mode selected as default option erroneously

### ISSUE THREAD

**Issue by seriouscatsoserious** [barebitcoin/sidesail#62]
![image](https://github.com/barebitcoin/sidesail/assets/121734574/f8459786-41dd-4eea-b531-4789153c466d)

On Windows 10. Not sure if system theme is what is being selected on init, or dark, but either way, Light theme is selected despite my theme being dark. Can still be clicked and set to light.

**Comment by octobocto** [comment]
Fixed!
