### ISSUE TITLE
Balances don't update

### ISSUE THREAD

**Issue by seriouscatsoserious** [barebitcoin/sidesail#65]
![image](https://github.com/barebitcoin/sidesail/assets/121734574/7e5df307-20bf-4f73-890a-644f17849284)

On Windows 10 as depicted in images

![image](https://github.com/barebitcoin/sidesail/assets/121734574/9db90b98-bcf6-4ff1-ba08-26f5ada8d18f)

**Comment by torkelrogstad** [comment]
Thanks for the report! Did you try and see if the `getbalance` and `getunconfirmedbalance` RPCs reported different numbers?

**Comment by octobocto** [comment]
I think this had to do with BMMing. Reopen if it happens again.
